version: '3.4'

services:
  app_base: &app_base
    build:
      context: .
      dockerfile: ./Dockerfile
    image: rails-boilerplate:1.0.0
    tmpfs:
      - /tmp

  app:
    <<: *app_base
    stdin_open: true
    tty: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
    environment:
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - RAILS_ENV=development
      - DATABASE_HOST=mysql
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '3000:3000'

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - ./containers/db:/etc/mysql/conf.d/
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306

volumes:
  mysql:
  bundle:
  rails_cache:
